language: generic 

sudo: required
services:
    - docker

before_install:
    - docker build -t funkrider/docker-react -f Dockerfile.dev

script:
  - docker run -e CI=true funkrider/docker-react npm run test
